stages:
  - build
  - deploy

cache:
  paths:
    - .npm/

before_script:
  - ["export PIPELINE_INFO=\"$CI_PIPELINE_ID-$CI_COMMIT_REF_NAME-$(date +%Y%m%d%H%M%S)-$CI_COMMIT_SHA\""]
  - ["echo \"Pipeline Info: $PIPELINE_INFO\""]

build_storybook:
  stage: build
  image: node:20
  script:
    - cd practice1
    - npm install
    - npm ci --cache .npm --prefer-offline
    - npm run build-storybook
  artifacts:
    paths:
      - practice1/storybook-static/
  only:
    - merge_requests

deploy_to_vercel:
  stage: deploy
  needs:
    - build_storybook
  image: node:20
  before_script:
    - cd practice1
    - npm i -g vercel
  script:
    - vercel --token $VERCEL_TOKEN --prod ./storybook-static
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "practice-01"'
      when: always
    - when: never
